# Generated by Django 5.0.2 on 2024-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('attendees', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
